"""
Multi-operator scalar basis and Euclidean correlator matrices.

This module constructs several gauge-invariant scalar operators from the same
underlying gauge configuration.

The current basis is generated by applying different numbers of spatial
smearing steps before constructing the scalar glueball-style time-slice
operator.

For operators O_i(t), the connected correlator matrix is

    C_ij(tau)
        =
        < O_i(t) O_j(t + tau) >
        -
        <O_i><O_j>.

A matrix-valued correlator enables variational and generalized-eigenvalue
methods in later spectroscopy phases.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ymlab.glueball import scalar_glueball_time_series
from ymlab.lattice import Lattice
from ymlab.smearing import smear_spatial_links


@dataclass(frozen=True)
class OperatorBasis:
    """Definition of a scalar operator basis."""

    names: tuple[str, ...]
    smearing_levels: tuple[int, ...]
    alpha: float
    time_direction: int


@dataclass(frozen=True)
class CorrelatorMatrixResult:
    """Connected Euclidean correlator matrix."""

    lags: np.ndarray
    correlation_matrices: np.ndarray
    raw_correlation_matrices: np.ndarray
    operator_means: np.ndarray
    number_of_configurations: int
    number_of_operators: int
    temporal_extent: int


def create_smearing_basis(
    smearing_levels: list[int] | tuple[int, ...],
    alpha: float,
    time_direction: int,
) -> OperatorBasis:
    """
    Create an operator basis indexed by smearing level.
    """
    levels = tuple(
        int(level)
        for level in smearing_levels
    )

    if len(levels) == 0:
        raise ValueError(
            "At least one smearing level is required."
        )

    if any(
        level < 0
        for level in levels
    ):
        raise ValueError(
            "Smearing levels must be nonnegative."
        )

    if len(set(levels)) != len(levels):
        raise ValueError(
            "Smearing levels must be unique."
        )

    if not 0.0 <= alpha <= 1.0:
        raise ValueError(
            "alpha must satisfy 0 <= alpha <= 1."
        )

    names = tuple(
        f"scalar_smear_{level}"
        for level in levels
    )

    return OperatorBasis(
        names=names,
        smearing_levels=levels,
        alpha=float(alpha),
        time_direction=int(
            time_direction
        ),
    )


def measure_operator_basis(
    lattice: Lattice,
    basis: OperatorBasis,
) -> np.ndarray:
    """
    Measure all basis operators on one lattice configuration.

    Output shape:

        (number_of_operators, temporal_extent).
    """
    if (
        basis.time_direction < 0
        or basis.time_direction >= lattice.dim
    ):
        raise ValueError(
            "Basis time direction is invalid "
            "for this lattice."
        )

    measurements = []

    for level in basis.smearing_levels:
        smeared = smear_spatial_links(
            lattice=lattice,
            time_direction=basis.time_direction,
            alpha=basis.alpha,
            steps=level,
        )

        operator = scalar_glueball_time_series(
            lattice=smeared,
            time_direction=basis.time_direction,
        )

        measurements.append(
            operator
        )

    return np.asarray(
        measurements,
        dtype=float,
    )


def periodic_cross_correlation(
    series_a: np.ndarray,
    series_b: np.ndarray,
) -> np.ndarray:
    """
    Compute a periodic Euclidean cross-correlation.

    For two operator time series A(t) and B(t),

        C_AB(tau)
            =
            (1/T) sum_t
            A(t) B(t + tau).
    """
    series_a = np.asarray(
        series_a,
        dtype=float,
    )

    series_b = np.asarray(
        series_b,
        dtype=float,
    )

    if (
        series_a.ndim != 1
        or series_b.ndim != 1
    ):
        raise ValueError(
            "Input series must be one-dimensional."
        )

    if len(series_a) != len(series_b):
        raise ValueError(
            "Input series must have the same length."
        )

    if len(series_a) < 2:
        raise ValueError(
            "Need at least two Euclidean time slices."
        )

    if (
        not np.all(
            np.isfinite(series_a)
        )
        or not np.all(
            np.isfinite(series_b)
        )
    ):
        raise ValueError(
            "Input series must contain finite values."
        )

    temporal_extent = len(
        series_a
    )

    return np.asarray(
        [
            np.mean(
                series_a
                * np.roll(
                    series_b,
                    -lag,
                )
            )
            for lag in range(
                temporal_extent
            )
        ],
        dtype=float,
    )


def ensemble_correlator_matrix(
    operator_ensemble: np.ndarray,
) -> CorrelatorMatrixResult:
    """
    Compute a connected Euclidean correlator matrix.

    Input shape:

        (
            configurations,
            operators,
            temporal_extent,
        )

    Output matrix shape:

        (
            temporal_extent,
            operators,
            operators,
        ).
    """
    ensemble = np.asarray(
        operator_ensemble,
        dtype=float,
    )

    if ensemble.ndim != 3:
        raise ValueError(
            "Expected ensemble shape "
            "(configurations, operators, temporal_extent)."
        )

    (
        number_of_configurations,
        number_of_operators,
        temporal_extent,
    ) = ensemble.shape

    if number_of_configurations < 2:
        raise ValueError(
            "Need at least two configurations."
        )

    if number_of_operators < 1:
        raise ValueError(
            "Need at least one operator."
        )

    if temporal_extent < 2:
        raise ValueError(
            "Need at least two Euclidean time slices."
        )

    if not np.all(
        np.isfinite(ensemble)
    ):
        raise ValueError(
            "Operator ensemble must contain finite values."
        )

    operator_means = np.mean(
        ensemble,
        axis=(0, 2),
    )

    raw = np.zeros(
        (
            temporal_extent,
            number_of_operators,
            number_of_operators,
        ),
        dtype=float,
    )

    for configuration_index in range(
        number_of_configurations
    ):
        configuration = ensemble[
            configuration_index
        ]

        for i in range(
            number_of_operators
        ):
            for j in range(
                number_of_operators
            ):
                raw[:, i, j] += (
                    periodic_cross_correlation(
                        configuration[i],
                        configuration[j],
                    )
                )

    raw /= number_of_configurations

    connected = np.empty_like(
        raw
    )

    for i in range(
        number_of_operators
    ):
        for j in range(
            number_of_operators
        ):
            connected[:, i, j] = (
                raw[:, i, j]
                - operator_means[i]
                * operator_means[j]
            )

    return CorrelatorMatrixResult(
        lags=np.arange(
            temporal_extent,
            dtype=int,
        ),
        correlation_matrices=connected,
        raw_correlation_matrices=raw,
        operator_means=np.asarray(
            operator_means,
            dtype=float,
        ),
        number_of_configurations=(
            number_of_configurations
        ),
        number_of_operators=(
            number_of_operators
        ),
        temporal_extent=(
            temporal_extent
        ),
    )


def symmetrize_correlator_matrix(
    matrices: np.ndarray,
) -> np.ndarray:
    """
    Symmetrize each operator-space matrix.

    C -> (C + C^T) / 2.
    """
    matrices = np.asarray(
        matrices,
        dtype=float,
    )

    if matrices.ndim != 3:
        raise ValueError(
            "Expected matrix array with shape "
            "(lags, operators, operators)."
        )

    if (
        matrices.shape[1]
        != matrices.shape[2]
    ):
        raise ValueError(
            "Operator matrices must be square."
        )

    return 0.5 * (
        matrices
        + np.swapaxes(
            matrices,
            1,
            2,
        )
    )


def maximum_matrix_asymmetry(
    matrices: np.ndarray,
) -> float:
    """
    Return the maximum absolute C_ij - C_ji discrepancy.
    """
    matrices = np.asarray(
        matrices,
        dtype=float,
    )

    if matrices.ndim != 3:
        raise ValueError(
            "Expected a 3D matrix array."
        )

    if (
        matrices.shape[1]
        != matrices.shape[2]
    ):
        raise ValueError(
            "Operator matrices must be square."
        )

    difference = (
        matrices
        - np.swapaxes(
            matrices,
            1,
            2,
        )
    )

    return float(
        np.max(
            np.abs(
                difference
            )
        )
    )


def correlation_matrix_eigenvalues(
    matrices: np.ndarray,
    symmetrize: bool = True,
) -> np.ndarray:
    """
    Compute eigenvalues of each Euclidean-time correlation matrix.
    """
    matrices = np.asarray(
        matrices,
        dtype=float,
    )

    if matrices.ndim != 3:
        raise ValueError(
            "Expected a 3D matrix array."
        )

    if (
        matrices.shape[1]
        != matrices.shape[2]
    ):
        raise ValueError(
            "Operator matrices must be square."
        )

    working = (
        symmetrize_correlator_matrix(
            matrices
        )
        if symmetrize
        else matrices
    )

    values = []

    for matrix in working:
        if symmetrize:
            eigenvalues = np.linalg.eigvalsh(
                matrix
            )
        else:
            eigenvalues = np.linalg.eigvals(
                matrix
            )

        values.append(
            eigenvalues
        )

    return np.asarray(
        values
    )
